{
 "title": "MetricsSimple",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Mono - CollectList", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "collectListDuration Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "collectListDuration_seconds{quantile=\"0.999\"}",
     "legendFormat": "{{instance}} - p999"
    }
   ]
  },
  {
   "title": "decodeValue_seconds",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "decodeValue_seconds{quantile=\"0.999\"}",
     "legendFormat": "{{instance}} - p999"
    }
   ]
  },
  {
   "title": "encodeValueWriteValue Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "encodeValueWriteValue_seconds{quantile=\"0.999\"}",
     "legendFormat": "{{instance}} - p999"
    }
   ]
  },
  {
   "title": "encodeValue Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "encodeValue_seconds{quantile=\"0.999\"}",
     "legendFormat": "{{instance}} - p999"
    }
   ]
  },
  {
   "title": "encodeValueAllocateBuffer Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "encodeValueAllocateBuffer_seconds{quantile=\"0.999\"}",
     "legendFormat": "{{instance}} - p999"
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Http Server RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (instance) (irate(http_server_requests_seconds_count[15s]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Http Server Times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (instance) (http_server_requests_seconds{uri=\"/dummy/{id}\", quantile=\"0.999\"})",
     "legendFormat": "{{instance}} - p999"
    }
   ]
  },
  { "title": "Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Http Client RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "max by (instance) (irate(http_client_requests_seconds_count[15s]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Http Client Times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (instance) (http_client_requests_seconds{quantile=\"0.999\"})",
     "legendFormat": "{{instance}} - p999"
    }
   ]
  },
  {
   "title": "JVM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "cpuUsage",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max by (instance) (process_cpu_usage)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "jvm_gc_pause_seconds_count Count",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "expr": "max by (instance) (jvm_gc_pause_seconds_count)",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "jvm_memory_committed_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (instance, area, id) (jvm_memory_committed_bytes{area=\"heap\"})",
       "legendFormat": "{{instance}} - {{area}} - {{id}}"
      }
     ]
    },
    {
     "title": "IRATE - jvm_memory_used_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (instance, area, id) (irate(jvm_memory_used_bytes{area=\"heap\"}[15s]))",
       "legendFormat": "{{instance}} - {{area}} - {{id}}"
      }
     ]
    },
    {
     "title": "JVM GC Allocated Bytes Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (instance) (rate(jvm_gc_memory_allocated_bytes_total[15s]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "jvm_memory_used_bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (instance, area, id) (jvm_memory_used_bytes{area=\"heap\"})",
       "legendFormat": "{{instance}} - {{area}} - {{id}}"
      }
     ]
    },
    {
     "title": "JVM GC Promoted Bytes Total",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "max by (instance) (rate(jvm_gc_memory_promoted_bytes_total[15s]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}