{
 "title": "Metrics",
 "time": { "from": "2024-06-19T22:10:33.000Z", "to": "now" },
 "panels": [
  { "title": "Client Internals", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "managerConnect Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "max by (instance) (managerConnect_seconds_count)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "managerConnect Times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "max by (instance) \n    ((increase(managerConnect_seconds_sum[15s])\n    /   \n    increase(managerConnect_seconds_count[15s])))\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IRATE leaseConnection Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "max by (instance) (irate(leaseConnection_seconds_count[15s]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "leaseConnection Times",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "max by (instance) \n    ((increase(leaseConnection_seconds_sum[15s])\n    /   \n    increase(leaseConnection_seconds_count[15s])))\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "IRATE discardConnection Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "max by (instance) (irate(discardConnection_seconds_count[15s]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "discardConnection Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "max by (instance) \n    ((increase(discardConnection_seconds_sum[15s])\n    /   \n    increase(discardConnection_seconds_count[15s])))\n",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "IRATE - jvm_memory_committed_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (instance, area, id) (irate(jvm_memory_committed_bytes{area=\"heap\"}[15s]))",
     "legendFormat": "{{instance}} - {{area}} - {{id}}"
    }
   ]
  },
  {
   "title": "IRATE - jvm_memory_used_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (instance, area, id) (irate(jvm_memory_used_bytes{area=\"heap\"}[15s]))",
     "legendFormat": "{{instance}} - {{area}} - {{id}}"
    }
   ]
  },
  {
   "title": "jvm_memory_committed_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (instance, area, id) (jvm_memory_committed_bytes{area=\"heap\"})",
     "legendFormat": "{{instance}} - {{area}} - {{id}}"
    }
   ]
  },
  {
   "title": "jvm_memory_used_bytes",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (instance, area, id) (jvm_memory_used_bytes{area=\"heap\"})",
     "legendFormat": "{{instance}} - {{area}} - {{id}}"
    }
   ]
  },
  {
   "title": "JVM GC Allocated Bytes Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (instance) (rate(jvm_gc_memory_allocated_bytes_total[15s]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "JVM GC Promoted Bytes Total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (instance) (rate(jvm_gc_memory_promoted_bytes_total[15s]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Buffer Total Capacity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (instance) (jvm_buffer_total_capacity_bytes{id=\"direct\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Http Server RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "max by (instance) (rate(http_server_requests_seconds_count[15s]))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Http Server Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (instance) \n    ((increase(http_server_requests_seconds_sum[15s])\n    /   \n    increase(http_server_requests_seconds_count[15s])))",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Http Server Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "max by (instance) (http_server_requests_seconds_max)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Client",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 72 },
   "collapsed": true,
   "panels": [
    {
     "title": "Http Client RPS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "max by (instance) (rate(http_client_requests_seconds_count[15s]))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Http Client Times",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (instance) \n    ((increase(http_client_requests_seconds_sum[15s])\n    /   \n    increase(http_client_requests_seconds_count[15s])))",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Http Client Max",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "max by (instance) (http_client_requests_seconds_max)",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  }
 ]
}