global:
  scrape_interval: 5s
  scrape_timeout: 2s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: []
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: prometheus1
    honor_timestamps: true
    scrape_interval: 5s
    scrape_timeout: 2s
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - host.docker.internal:8081
        labels:
          instance: "nettyOne"
  - job_name: prometheus2
    honor_timestamps: true
    scrape_interval: 5s
    scrape_timeout: 2s
    metrics_path: /actuator/prometheus
    scheme: http
    static_configs:
      - targets:
          - host.docker.internal:8082
        labels:
          instance: "nettyTwo"